language: java
script:
  - mvn clean install
os: osx
jdk:
  - openjdk15
deploy:
  provider: script
  script: bash scripts/upload.bash $TRAVIS_BUILD_NUMBER $API_KEY
  cleanup: true
branches:
  only:
    - master
    - dev