language: java
script:
  - mvn clean install
os: osx
jdk:
  - openjdk15
deploy:
  - provider: script
    script: bash scripts/upload_STABLE.bash $TRAVIS_BUILD_NUMBER $API_KEY
    cleanup: false
    on:
      branch: master
  - provider: script
    script: bash scripts/upload_DEV.bash $TRAVIS_BUILD_NUMBER $API_KEY
    cleanup: false
    on:
      branch: dev
  - provider: script
    script: bash scripts/upload_INDEV.bash $TRAVIS_BUILD_NUMBER $API_KEY
    cleanup: false
    on:
      branch: indev
branches:
  only:
    - master
    - release_candidates
    - production
