language: java
script: mvn clean install
os: osx
jdk:
  - openjdk15
deploy:
  - provider: script
    script: bash scripts/upload_RELEASE.bash $TRAVIS_BUILD_NUMBER $API_KEY
    cleanup: false
    on:
      branch: release
  - provider: script
    script: bash scripts/upload_RELEASE_CANDIDATE.bash $TRAVIS_BUILD_NUMBER $API_KEY
    cleanup: false
    on:
      branch: release_candidate
  - provider: script
    script: bash scripts/upload_DEVELOPMENT.bash $TRAVIS_BUILD_NUMBER $API_KEY
    cleanup: false
branches:
  only:
    - master
    - release_candidate
    - release
    - improve_binary_releasing
