#Thank you for using PunishmentManager, I hope you enjoy using the plugin.
#every string where there is a (*) needs to be contained in a single '

debug: true
dev: true

server: survival
servergroup:
  - global
# !!!!!IF THIS OPTION IS NOT ENABLED NOTHING WILL BE SAVED!!!!!
database:
  enabled: true
  #make sure this option is correctly spelled including capitalization
  #there are more to come don't worry
  type: "me.superbiebel.defaultmysqldatabase.mysql.MySQLDatabase"

reflectionpath:
  #deprecated
  datahandlerdriver: "me.superbiebel.defaultdatahandler.DefaultDataHandler"
  #deprecated
  databasedriver: "me.superbiebel.defaultmysqldatabase.mysql.MySQLDatabase"
  #deprecated
  cachedriver: "me.superbiebel.defaultehcache.DefaultEhCache"
  standalonedatahandlerdriver: "me.superbiebel.defaultdatahandler.OffenseProcessingDefaultDataHandler"
  standalonedatabasedriver: "me.superbiebel.defaultmysqldatabase.mysql.OffenseProcessingMySQLDatabase"
  standalonecachedriver: "me.superbiebel.defaultehcache.OffenseProcessingEhCache"



#deprecated
datahandler:
  type: "me.superbiebel.defaultdatahandler.DefaultDataHandler"

offenseprocessor:
  type: "me.superbiebel.defaultoffenseprocessor.DefaultOffenseProcessorFactory"

MySQL:
  db: 'punishplugin'
  # (*)
  host: '127.0.0.1'
  # (*)
  username: 'plugintest'
  # (*)
  password: 'plugintest'
  # (*)
  port: 3306
  useSSL: false
  #extra options for hikari for the people who know how to use it!
  #I am not responsible for any corruptions or issues that might arise when using this the wrong way!
  #if you use this you acknowledge that issues that have to do with database corruptions or mysql problems will be of a lower priority and that you can receive less support then normal.
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048

messages:
  noPermissionMessage: "&r&4&lPunishment&b&lManager&4&l>> &4&lYou do not have the permission for that!"

cache:
  type: "me.superbiebel.defaultehcache.DefaultEhCache"
  # write here how high the offense id goes,setting it too low can cause offenses to not show up when ur trying to register one
  offense_id_max: 50 #currently not used
































#This is the end of the config, no really! It is!
#---------------------------------------------------------------------------------------------------------------------------------------------------
#DO NOT TOUCH!!! TOUCHING = BREAKING THE WHOLE PLUGIN!!!!
config_version: indev

