#Thank you for using PunishmentManager, I hope you enjoy using the plugin.
#every string where there is a (*) needs to be contained in a single '

debug: true
server: survival
servergroup:
  - global
# !!!!!IF THIS OPTION IS NOT ENABLED NOTHING WILL BE SAVED!!!!!
MySQL:
  enabled: true
  db: 'minecraft'
  host: 'localhost'
  username: 'plugintest'
  password: 'joren'
  port: 3306
  useSSL: false
  #extra options for hikari for the people who know how to use it!
  #I am not responsible for any corruptions or issues that might arise when using this the wrong way!
  #if you use this you acknowledge that issues that have to do with database corruptions or mysql problems will be of a lower priority and that you can receive less support then normal.
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048

